// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDIDlGY0i_kqv1XurAzfdu0oTzYTzheIs',
    appId: '1:57136751205:web:21056f347a4c124dff5c8c',
    messagingSenderId: '57136751205',
    projectId: 'esd-monitoring-2db90',
    authDomain: 'esd-monitoring-2db90.firebaseapp.com',
    storageBucket: 'esd-monitoring-2db90.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc3uGzTixW1_xymiI8AQxmF-UiWFGjFLM',
    appId: '1:591804418697:android:66930957a1c8cb60e21458',
    messagingSenderId: '591804418697',
    projectId: 'bookingpetcare',
    storageBucket: 'bookingpetcare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2jlcZ62IAiada3hF6qlE2csHMH1QSXjg',
    appId: '1:57136751205:ios:af30eaec87a28dffff5c8c',
    messagingSenderId: '57136751205',
    projectId: 'esd-monitoring-2db90',
    storageBucket: 'esd-monitoring-2db90.appspot.com',
    iosBundleId: 'com.avic.avicSmartfactory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2jlcZ62IAiada3hF6qlE2csHMH1QSXjg',
    appId: '1:57136751205:ios:af30eaec87a28dffff5c8c',
    messagingSenderId: '57136751205',
    projectId: 'esd-monitoring-2db90',
    storageBucket: 'esd-monitoring-2db90.appspot.com',
    iosBundleId: 'com.avic.avicSmartfactory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDIDlGY0i_kqv1XurAzfdu0oTzYTzheIs',
    appId: '1:57136751205:web:08f0f412757a6c24ff5c8c',
    messagingSenderId: '57136751205',
    projectId: 'esd-monitoring-2db90',
    authDomain: 'esd-monitoring-2db90.firebaseapp.com',
    storageBucket: 'esd-monitoring-2db90.appspot.com',
  );
}
